---
- name: install nginx and run delete the nxinx after few seconds
  hosts: all
  become: yes
  tasks:
  - name: update the package manager
    yum:
      name: '*'
      state: latest
    when: ansible_os_family == 'ReadHat'
  - name: update package for ubuntu
    apt:
      update_cache: yes
    when: ansible_os_family == 'ubuntu'
  - name: install nginx in ReadHat
    yum: 
      name: nginx
      state: present
    when: ansible_os_family == 'ReadHat'
  - name: install nginx in ubuntu
    apt:
      name: nginx
      state: present
    when: ansible_os_family == 'ubuntu'
  - name: start nginx service
    service:
      name: nginx
      state: started
  